from __future__ import annotations
from typing import Any

TABLE_PRIORITY = [
    "samplelist",
    "ReadsQC.xls",
    "Statistic_Reads.xls",
    "spikein_align.xls",
    "AlignmentQC.xls",
    "spearman_Corr_readCounts.tab",
    "Correlation_Summary_1.xls",
    "FRiP_score.xls",
    "Samples_peak_number_stat.xls",
    "FRiP.xls",
    "Samples.rRNA_Globin_stat.xls",
    "Samples.ExpRange.xls",
    "CUTTag_report.html",
    "report.html",
]

STRUCTURED_TABLE_FILES = {
    "readsqc.xls",
    "statistic_reads.xls",
    "spikein_align.xls",
    "alignmentqc.xls",
    "samples_peak_number_stat.xls",
    "spearman_corr_readcounts.tab",
    "frip_score.xls",
    "frip.xls",
    "samples.rrna_globin_stat.xls",
    "samples.exprange.xls",
}

LOG_NAME_TOKENS = ("stderr", "stdout", "snakemake", "pipeline", "workflow", "error", "traceback", "crash")

PREFLIGHT_CONFIG_KEYS = {
    "project",
    "project_name",
    "Sequencing",
    "scripts",
    "pipeline",
    "workflow",
    "assay",
    "project_type",
    "species",
    "sample",
    "samplelist",
    "samplist",
    "output",
    "output_dir",
    "raw_fastq_dir",
    "sequencing_mode",
    "seq_length",
    "adapter_type",
    "trimming_tool",
    "remove_duplicates",
    "spikein_analysis",
    "macs3_qvalue",
    "macs2_qvalue",
    "TOP_PEAKS_NUM",
    "KNOWN_MOTIF_TOP_N",
    "organelle_chroms",
    "genome",
    "reference",
    "db_root",
    "effective_genome_size",
    "peak_caller",
    "peak_calling",
    "tss_region",
    "blacklist_bed",
    "report_lang",
}

PROFESSIONAL_RULES: dict[str, Any] = {
    "adapter_percent": {
        "label": "Adapter-detected raw-read rate",
        "unit": "%",
        "warning": {"op": ">", "value": 20.0},
        "critical": {"op": ">", "value": 50.0},
        "source_field": "Adapter",
        "definition": "原始 reads 中检测到接头相关序列的 reads 比例。",
        "denominator": "raw reads",
        "assumption": "该指标描述 trimming 前的原始 reads；不能单独证明 clean reads 中仍有接头残留。",
        "interpretation": "需结合 clean FASTQ 的 Adapter Content、clean reads 保留率和 fragment size 判断是否存在处理后残留或短片段 read-through。",
        "downstream_impact": "只有在接头相关序列造成 reads 丢失或 clean reads 仍有残留时，才可能进一步影响比对和富集分析。",
    },
    "q30_ratio": {
        "label": "Q30",
        "unit": "",
        "warning": {"op": "<", "value": 0.93},
        "critical": {"op": "<", "value": 0.90},
        "source_field": "Q30",
        "definition": "碱基质量值不低于 Q30 的比例。",
        "denominator": "total bases",
        "assumption": "通常使用测序质控工具统计的 clean reads 或 raw reads 碱基质量比例。",
        "interpretation": "Q30 偏低提示测序质量下降，需要结合 raw QC 和过滤比例判断。",
        "downstream_impact": "增加错配风险，可能降低比对率和唯一比对率。",
    },
    "mapping_rate_percent": {
        "label": "Mapping rate",
        "unit": "%",
        "warning": {"op": "<", "value": 70.0},
        "critical": {"op": "<", "value": 60.0},
        "source_field": "Mapping(%)",
        "definition": "reads 成功比对到参考基因组的比例。",
        "denominator": "alignment input reads",
        "assumption": "需确认参考基因组版本、比对工具参数和是否包含细胞器染色体。",
        "interpretation": "比对率偏低通常与参考基因组、污染、样本质量或 reads 组成异常相关。",
        "downstream_impact": "降低可用于后续 peak calling、FRiP 和相关性分析的有效 reads。",
    },
    "unique_mapping_rate_percent": {
        "label": "Unique mapping rate",
        "unit": "%",
        "warning": {"op": "<", "value": 30.0},
        "critical": {"op": "<", "value": 20.0},
        "source_field": "Unique(%)",
        "definition": "唯一比对到参考基因组位置的 reads 比例。",
        "denominator": "alignment input reads",
        "assumption": "低唯一比对可能来自重复序列、细胞器 reads、参考基因组不匹配或多重比对策略。",
        "interpretation": "唯一比对率偏低会削弱后续富集、peak 和相关性判断的可靠性。",
        "downstream_impact": "直接影响 peak calling、FRiP、样本相关性和差异分析可信度。",
    },
    "duplicate_rate_percent": {
        "label": "Duplicate rate",
        "unit": "%",
        "warning": {"op": ">", "value": 30.0},
        "critical": {"op": ">", "value": 50.0},
        "source_field": "Duplicate(%)",
        "definition": "被判定为重复的 reads 或 fragments 比例。",
        "denominator": "mapped reads/fragments",
        "assumption": "需结合 library complexity；CUT&Tag 中来自真实富集区域的重复不应被简单等同于失败。",
        "interpretation": "重复率偏高可能来自低复杂度文库，也可能由高比例细胞器 reads 推高。",
        "downstream_impact": "可能降低有效文库复杂度，并影响 peak 强度和定量稳定性。",
    },
    "mt_rate_percent": {
        "label": "Organelle alignment rate",
        "unit": "%",
        "warning": {"op": ">", "value": 10.0},
        "critical": {"op": ">", "value": 30.0},
        "source_field": "chrMT/Pt(%)",
        "definition": "比对到项目所配置细胞器染色体的 reads 比例。",
        "denominator": "mapped reads",
        "assumption": "必须根据 species/reference 和 organelle_chroms 判断该字段代表线粒体、叶绿体/质体或其他细胞器。",
        "interpretation": "细胞器 reads 占比需要结合物种和流程过滤策略解释。",
        "downstream_impact": "显著压缩核基因组有效 reads，造成 Unique、FRiP、peak 和相关性异常。",
    },
    "frip_ratio": {
        "label": "FRiP",
        "unit": "",
        "warning": {"op": "<", "value": 0.20},
        "critical": {"op": "<", "value": 0.10},
        "source_field": "FRiP",
        "definition": "落在 peak 区域内的 reads 占比，用于衡量富集质量。",
        "denominator": "usable mapped reads/fragments",
        "assumption": "IgG/Input/control 的 FRiP 不能和实验样本套用相同解释；口径依赖 peak set 和 usable reads 定义。",
        "interpretation": "FRiP 偏低提示富集效率不足或 peak calling 质量受限。",
        "downstream_impact": "影响 peak 可信度、差异 peak 和 motif/enrichment 分析。",
    },
    "correlation": {
        "label": "Sample correlation",
        "unit": "",
        "warning": {"op": "<", "value": 0.80},
        "critical": {"op": "<", "value": 0.60},
        "source_field": "spearman correlation",
        "definition": "样本间 read count 信号的一致性，通常使用 Spearman 相关系数。",
        "denominator": "genomic bins or peak/read count features",
        "assumption": "应优先比较同组生物学重复；不同处理组或 IgG/control 与实验样本不应强行要求高度相关。",
        "interpretation": "样本相关性偏低提示重复一致性不足或样本间存在系统差异。",
        "downstream_impact": "影响重复合并、差异分析和最终生物学解释可靠性。",
    },
    "mrna_ratio_percent": {
        "label": "mRNA reads ratio",
        "unit": "%",
        "warning": {"op": "<", "value": 30.0},
        "critical": {"op": "<", "value": 15.0},
        "source_field": "mRNA_ratio(%)",
        "definition": "比对到 mRNA 区域的 reads 占总 mapped reads 的比例，反映 rRNA 去除效率和文库质量。",
        "denominator": "total mapped reads",
        "assumption": "阈值依赖 rRNA 去除方案（rRNA-depletion vs polyA-selection）；polyA 建库通常 > 60%。",
        "interpretation": "mRNA 比例偏低提示 rRNA 残留、样本降解或建库失败；结合 rRNA 比例判断根因。",
        "downstream_impact": "有效转录组 reads 减少，影响基因检测数量、定量精度和差异分析灵敏度。",
    },
    "rrna_ratio_percent": {
        "label": "rRNA reads ratio",
        "unit": "%",
        "warning": {"op": ">", "value": 30.0},
        "critical": {"op": ">", "value": 60.0},
        "source_field": "rRNA_ratio(%)",
        "definition": "比对到 rRNA 序列的 reads 比例，反映 rRNA 污染程度。",
        "denominator": "total mapped reads",
        "assumption": "rRNA 去除不彻底或 rRNA depletion kit 失效时该值升高；不同物种 rRNA 比例基线有差异。",
        "interpretation": "rRNA 比例过高直接消耗有效测序量，可能导致数据质量不足以支撑下游分析。",
        "downstream_impact": "mRNA reads 减少，基因定量噪声增大，差异分析效力下降。",
    },
    "detected_gene_count": {
        "label": "Detected genes",
        "unit": "genes",
        "warning": {"op": "<", "value": 10000},
        "critical": {"op": "<", "value": 5000},
        "source_field": "Sum.",
        "definition": "表达量大于 0 的基因数量，反映数据覆盖度和文库质量。",
        "denominator": "annotated genes in reference",
        "assumption": "阈值依赖物种和测序深度；人类通常检测 15,000–20,000+ 个基因。",
        "interpretation": "检测基因数偏少提示测序深度不足、mRNA 比例偏低或样本质量问题。",
        "downstream_impact": "影响差异表达分析中低表达基因的检测能力和功能富集结果可靠性。",
    },
    "exon_ratio_percent": {
        "label": "Exon reads ratio",
        "unit": "%",
        "warning": {"op": "<", "value": 20.0},
        "critical": {"op": "<", "value": 10.0},
        "source_field": "mRNA_Exon_ratio(%)",
        "definition": "比对到外显子区域的 reads 占总 mapped reads 的比例。",
        "denominator": "total mapped reads",
        "assumption": "exon 比例与建库方式（polyA/total RNA）和物种基因结构相关。",
        "interpretation": "外显子比例偏低提示基因组污染或 pre-mRNA 大量存在（RNA 降解或样本来源异常）。",
        "downstream_impact": "影响基因表达定量的信噪比，外显子覆盖不均匀会影响 FPKM/TPM 计算准确性。",
    },
}

QUESTION_FILE_HINTS: dict[str, list[str]] = {
    "qc": ["ReadsQC.xls", "Statistic_Reads.xls", "1.ReadsQC.readme.txt"],
    "alignment": ["AlignmentQC.xls", "2.1AlignmentStat.readme.txt"],
    "correlation": ["spearman_Corr_readCounts.tab", "Correlation_Summary_1.xls", "3.Correlation.readme.txt"],
    "peak": ["FRiP_score.xls", "FRiP_raw.txt", "Samples_peak_number_stat.xls", "5.1PeakStat.readme.txt", "5.1PeakStat"],
    "frip": ["FRiP_score.xls", "FRiP.xls", "FRiP_raw.txt", "peakFrip"],
    "spikein": ["spikein_align.xls", "Spikein"],
    "diagnostic": [
        "ReadsQC.xls",
        "Statistic_Reads.xls",
        "AlignmentQC.xls",
        "spikein_align.xls",
        "FRiP.xls",
        "FRiP_score.xls",
        "FRiP_raw.txt",
        "peakFrip",
        "Samples_peak_number_stat.xls",
        "spearman_Corr_readCounts.tab",
        "Correlation_Summary_1.xls",
        "Samples.rRNA_Globin_stat.xls",
        "Samples.ExpRange.xls",
    ],
    "diff": [
        "final_anno",
        "GO_up",
        "GO_down",
        "Pathway",
        "DiffPeak.readme.txt",
        "GOList.readme.txt",
        "PathwayList.readme.txt",
        "DiffAnalysis",
        "diff",
        "DEG",
    ],
    "motif": ["knownResults.txt", "homerMotifs.all.motifs", "_meme.txt", "Motify.readme.txt", "Motifyhtml", "MotifyAnalysis", "Motif", "meme"],
    "igv": ["ForIGV", "bigwig", "bw", "bedgraph"],
    "overview": ["CUTTag_report.html", "README.txt", "report.html", "ReadsQC.xls", "AlignmentQC.xls", "Statistic_Reads.xls"],
    "log": [".log", "error", "stderr", "stdout", "pipeline", "snakemake", "workflow"],
}

TARGET_METRIC_FILE_HINTS: dict[str, tuple] = {
    "adapter_percent": ("ReadsQC.xls", "Statistic_Reads.xls"),
    "q30_ratio": ("ReadsQC.xls", "Statistic_Reads.xls"),
    "mapping_rate_percent": ("AlignmentQC.xls",),
    "unique_mapping_rate_percent": ("AlignmentQC.xls",),
    "duplicate_rate_percent": ("AlignmentQC.xls", "Statistic_Reads.xls"),
    "mt_rate_percent": ("AlignmentQC.xls",),
    "chrmt_pt_rate_percent": ("AlignmentQC.xls",),
    "frip": ("FRiP_score.xls", "FRiP.xls", "FRiP_raw.txt"),
    "frip_ratio": ("FRiP_score.xls", "FRiP.xls", "FRiP_raw.txt"),
    "correlation": ("spearman_Corr_readCounts.tab", "Correlation_Summary_1.xls"),
    "peak_count": ("Samples_peak_number_stat.xls",),
    "mrna_ratio_percent": ("Samples.rRNA_Globin_stat.xls",),
    "rrna_ratio_percent": ("Samples.rRNA_Globin_stat.xls",),
    "detected_gene_count": ("Samples.ExpRange.xls",),
}

SECONDARY_TEXT_HINTS: dict[str, list[str]] = {
    "diff": ["diff", "deg", "differential"],
    "motif": ["motif", "homer", "meme"],
    "igv": ["igv", "bigwig", "bedgraph", ".bw"],
    "log": [".log", "error", "stderr", "stdout"],
}

PIPELINE_FAILURE_TERMS = (
    "为什么失败",
    "为什么报错",
    "失败原因",
    "报错原因",
    "分析失败",
    "跑失败",
    "没跑完",
    "没有跑完",
    "没分析完",
    "没有分析完",
    "任务失败",
    "流程报错",
    "流程失败",
    "pipeline失败",
    "pipeline报错",
    "pipeline error",
    "pipeline failed",
    "why failed",
    "why error",
    "job failed",
    "task failed",
    "run failed",
    "什么错误",
    "什么报错",
    "查看报错",
    "看报错",
    "看错误",
    "查看错误",
    "项目失败",
    "项目报错",
    "项目错误",
    "出错了",
    "报错了",
    "失败了",
    "分析报错",
    "分析出错",
    "查看日志",
    "看日志",
    "看log",
    "查看log",
    "有报错",
    "有错误",
    "错误原因",
)

DIAGNOSTIC_TERMS = (
    "低",
    "偏低",
    "高",
    "偏高",
    "差",
    "不好",
    "不对",
    "异常",
    "太少",
    "太多",
    "怎么回事",
    "为什么",
    "失败",
    "不理想",
    "有问题",
    "low",
    "lower",
    "high",
    "higher",
    "bad",
    "poor",
    "abnormal",
    "wrong",
    "issue",
    "problem",
    "fail",
    "failed",
    "why",
    "报错",
    "错误",
    "日志",
    "错误日志",
    "log",
    "error",
)

INTERNAL_WORKFLOW_TERMS = (
    "流程",
    "脚本",
    "参数",
    "命令",
    "配置",
    "阈值",
    "qvalue",
    "q-value",
    "q值",
    "callpeak",
    "call peak",
    "snakefile",
    "snakemake",
    "workflow",
    "pipeline",
    "shell",
    "config",
    "script",
    "trimming",
    "macs",
    "bowtie",
)
